### ISSUE TITLE
Compatibility with relationship to translatable models

### ISSUE THREAD

**Issue by Voltra** [lara-zeus/translatable#8] opened 2024-05-21 13:28 UTC
Problem description:

In v3.2.81, translatable models with a relationship to another translatable model don't get that relationship's data updated on locale change via the language switch.

Expected Behavior:

It should switch to the translated version of the content for that relationship

Potential solution:

https://github.com/lara-zeus/translatable/blob/c00fbd28c6e37f2476498befb1925a071f414d18/src/Resources/Pages/EditRecord/Concerns/Translatable.php#L84

In my [PR](https://github.com/filamentphp/filament/pull/11450) I had encountered that issue, and using `$this->form->getState(false)` fixed it.

Versions:
- filament/filament 3.2.81
- filament/spatie-laravel-translatable-plugin 3.2.81
- ralphjsmit/laravel-filament-seo 1.3.2
- z3d0x/filament-fabricator 2.2.2

Setup:
- `\App\Models\Overrides\Page` extends `\Z3d0X\FilamentFabricator\Models\Page` and uses `\RalphJSmit\Laravel\SEO\Support\HasSEO` as well as `Spatie\Translatable\HasTranslations` (NB: the `seo` property is not part of the `$translatable` array since it's a relationship and not a db column)
- `\App\Models\Overrides\SEO` extends `\RalphJSmit\Laravel\SEO\Models\SEO` and uses `Spatie\Translatable\HasTranslations`
- `\App\Filament\Resources\PageResource` extends `\Z3d0X\FilamentFabricator\Resources\PageResource`, uses `Filament\Resources\Concerns\Translatable` and all related pages are properly overridden and configured
- A (filament) section for the `seo` relationship is displayed on the (edit or create) page, its translatable attributes are editable thanks to the section's schema

**Comment by Voltra** [comment] 2024-05-21 14:50
Testing has also been a bit difficult since it seems there's a DB mutation even when the page is exited without hitting save (or pressing ctrl+S).

With `$this->form->getState(false)` I can properly use the edit page. The rest remain unchanged.

**Comment by atmonshi** [comment] 2024-05-21 16:03
> With `$this->form->getState(false)` I can properly use the edit page. The rest remain unchanged.

ya, I saw that, the reason I didn't use it, that the file upload, when there is a translatable upload component it wont keep the state when switching the locale.

did some changes here: #9, and its working good with the upload issue, can you test it with the relation?

**Comment by Voltra** [comment] 2024-05-21 17:25
I'll try it, with a backup of my DB beforehand this time lol

**Comment by Voltra** [comment] 2024-05-27 20:44
Just tested it on a brand new page, the bug is still present

**Comment by atmonshi** [comment] 2024-06-13 02:00
how I can reproduce it without the extra packages?
never use these so dont know how they looks and what type of components they use?

or do you have a repo?

I do have a case where I use repeater with relation, it wont work and there is no chance to get it work :), hope your issue not related!

there is no direct way to know which of these attributes are a relation, so it wont look for its translations and store them correctly

**Comment by Voltra** [comment] 2024-06-13 16:19
I'll try to make a reproduction repo! It's not part of a repeater, but maybe there's a similar thing with grid/section/etc. ?

**Comment by atmonshi** [comment] 2024-06-13 16:26
yes unfortunately, did some digging last night, I think its impossible to handle relations, even inside grid or section

`getState`, `getRawState`, `$this-data`, they all return arrays, and cant tell if there is a relation to get the model and translatable attributes to save them etc...

if you on discord.. join [this thread](https://discord.com/channels/883083792112300104/1250588911550599220) talking about the locale switcher and more ideas :)

or maybe better to open new discussion in this repo?! let me know.

**Comment by Voltra** [comment] 2024-06-13 16:58
Will do! What's weird is that `getState(false)` works like a charm for my use cases

**Comment by atmonshi** [comment] 2024-06-13 17:36
did another stupid fix lol
[check this change](https://github.com/lara-zeus/translatable/pull/9/files#diff-b92f2a871ce569675d65f0270dfd822e1ce7293add2636d7055b49b200aa217bR85)

it doesn't break the upload, hopefully will also work in the relation with sections!

**Comment by atmonshi** [comment] 2024-06-13 18:09
using getState(false) will fix the relation but break the uploads

`array_merge` didnt help!

so its either the relations or the uploads, these the ones I test with not sure if there is others issues :)


>Testing has also been a bit difficult since it seems there's a DB mutation even when the page is exited without hitting save (or pressing ctrl+S).

I did get this too, the reasons is filament will save the relation before saving the record, and calling any of: getState or getRawState will trigger the saving

the `meta` is a relationship:

https://github.com/lara-zeus/translatable/assets/1952412/2eb744e4-928e-4bf9-866f-9d2e9ea9c896

**Comment by Voltra** [comment] 2024-06-13 20:17
> did another stupid fix lol [check this change](https://github.com/lara-zeus/translatable/pull/9/files#diff-b92f2a871ce569675d65f0270dfd822e1ce7293add2636d7055b49b200aa217bR85)
> 
> it doesn't break the upload, hopefully will also work in the relation with sections!

I'll have a look at this before making the repro repo (including a file upload too)

**Comment by atmonshi** [comment] 2024-06-13 20:22
I have this [repo](https://github.com/lara-zeus/translatable-demo), if you want to clone and test and add your case, so we all can test in one place. with all different scenarios

**Comment by atmonshi** [comment] 2024-06-13 20:24
also a note: this only working on edit, still figuring out the create page

**Comment by Khant-Nyar** [comment] 2024-06-20 04:18
in my case i have issue to save the record as json (array) cast with repeater but it work only for 1 language  

edit.php
```
<?php

namespace App\Filament\Resources\ProductCategoryResource\Pages;

use App\Filament\Resources\ProductCategoryResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Support\Arr;

class EditProductCategory extends EditRecord
{
    use EditRecord\Concerns\Translatable;

    protected static string $resource = ProductCategoryResource::class;

    protected function mutateFormDataBeforeFill(array $data): array
    {
        // if (is_string($data['advantages_content'])) {
        //     $data['advantages_content'] = json_decode($data['advantages_content'], true);
        // }
        return $data ;
    }

    public function getTranslatableLocales(): array
    {
        return static::getResource()::getTranslatableLocales();
    }
    public function setActiveLocale(string $locale): void
    {
        $this->updatingActiveLocale();
        $this->activeLocale = $locale;
        $this->updatedActiveLocale();
    }
    

    public function updatedActiveLocale() 
    {
        if (blank($this->oldActiveLocale)) {
            return;
        }
        // dd($this->record->advantages_content);
        $this->resetValidation();

        $translatableAttributes = static::getResource()::getTranslatableAttributes();

        $this->otherLocaleData[$this->oldActiveLocale] = Arr::only($this->form->getState(), $translatableAttributes);

        // $this->fillFormWithDataAndCallHooks([
        //     ...Arr::except($this->data, $translatableAttributes),
        //     ...$this->otherLocaleData[$this->activeLocale] ?? [],
        // ]);
        // dd($translatableAttributes);
        // $this->otherLocaleData[$this->oldActiveLocale] = Arr::only($this->data, $translatableAttributes);

        // Fix part - Start
        // dd(...Arr::except($this->data, $translatableAttributes));
        // $this->form->fill([
        //     ...Arr::except($this->data, $translatableAttributes),
        //     ...$this->otherLocaleData[$this->activeLocale] ?? [],
        // ]);
        // dd($this->data);
        unset($this->otherLocaleData[$this->activeLocale]);
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\LocaleSwitcher::make(),
            Actions\DeleteAction::make(),
        ];
    }
}

```

resourcepage.php

```
<?php

namespace App\Filament\Resources;

use App\Filament\Enums\AdvantageLayoutTypeEnum;
use App\Filament\Resources\ProductCategoryResource\Pages;
use App\Models\ProductCategory;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Concerns\Translatable;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Support\Str;

class ProductCategoryResource extends Resource
{
    use Translatable;

    protected static ?string $model = ProductCategory::class;

    protected static ?string $navigationIcon = 'heroicon-o-queue-list';

    protected static ?string $navigationGroup = 'Manage Products';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('name')
                    ->required()
                    ->maxLength(255)
                    ->live(onBlur: true)
                    ->afterStateUpdated(function (string $operation, $state, Forms\Set $set): void {
                        if ($operation !== 'create') {
                            return;
                        }
                        $set('slug', Str::slug($state));
                    }),

                Forms\Components\TextInput::make('slug')
                    ->disabled()
                    ->dehydrated()
                    ->required()
                    ->maxLength(255)
                    ->unique(ProductCategory::class, 'slug', ignoreRecord: true),
                Forms\Components\FileUpload::make('icon')
                    ->image(),
                Forms\Components\FileUpload::make('image')
                    ->image(),
                Forms\Components\TextInput::make('advantages_title')
                    ->required(),
                Forms\Components\Repeater::make('advantages_content')
                    ->schema([
                        Forms\Components\TextInput::make('order')
                            ->numeric()
                            ->required(),
                        Forms\Components\TextInput::make('title')
                            ->required(),
                        Forms\Components\FileUpload::make('img')
                            ->disk('public')
                            ->directory('advantages')
                            ->image(),
                        Forms\Components\MarkdownEditor::make('desc')
                            ->required(),
                        Forms\Components\Select::make('type')
                            ->options(AdvantageLayoutTypeEnum::class)
                            ->required(),
                    ])
                    ->minItems(1)
                    ->maxItems(4)
                    ->defaultItems(4)
                    ->addable(false)
                    ->deletable(false)
                    ->required()
                    ->columnSpanFull(),

            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('slug')
                    ->searchable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\ImageColumn::make('icon'),
                Tables\Columns\ImageColumn::make('image'),
                // Tables\Columns\TextColumn::make('advantages.title')
                //     ->searchable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index'  => Pages\ListProductCategories::route('/'),
            'create' => Pages\CreateProductCategory::route('/create'),
            'edit'   => Pages\EditProductCategory::route('/{record}/edit'),
        ];
    }
}

```

i have spend a lot of time in this ,nothing don't work with repeater + translateable

**Comment by Voltra** [comment] 2024-06-21 09:37
@Khant-Nyar Is your `advantages_content` a JSON column or a relationship? I use filament-fabricator and it has something similar for blocks and it's properly translatable. However you "need" to translate the whole column, not individual sub-fields.

Have you tried with `$this->form->getState(false)`? It usually solves issues on my end (but not all of them sadly).

**Comment by cawecoy** [comment] 2024-08-13 22:11
In order to make it possible to fix it in a convenient way, this PR should be merged into Filament main repo: https://github.com/filamentphp/filament/pull/13936

After that we can fix it by adding this to [src/Resources/Pages/EditRecord/Concerns/Translatable.php](https://github.com/lara-zeus/translatable/blob/0ece8d48487977093208ebc94c9038bb11aad029/src/Resources/Pages/EditRecord/Concerns/Translatable.php):

```php
protected ?array $shouldCallHooksBeforeExceptComponents = [];
```

Then we can use:

```php
$this->form->getState(shouldCallHooksBeforeExceptComponents: $this->shouldCallHooksBeforeExceptComponents)
```

And the user can overwrite the `$shouldCallHooksBeforeExceptComponents` array adding the Repeater's component name into it.

E.g. suppose the user wants this Repeater to be translatable:

```php
Repeater::make('answers')
```

Then this should be done:

```php
class EditProductCategory extends EditRecord
{
    use EditRecord\Concerns\Translatable;
    protected ?array $shouldCallHooksBeforeExceptComponents = ['answers'];
    
    // ...
}
```

Deeper improvement insight: we can loop through the form's components looking for problematic components like Repeaters (components within relationship I guess) and adding their names into `$shouldCallHooksBeforeExceptComponents` automatically so the user should do nothing.

**Comment by Voltra** [comment] 2024-08-14 11:58
Sounds great! I'd rename the property to `$translatableIgnoreBeforeHooks` or `$translatableIgnoreBeforeHooksFor` to avoid future name conflicts

**Comment by cawecoy** [comment] 2024-08-16 14:52
Updates: we can't proceed with the solution proposed by me, because it relied on a PR to Filament, which was close and not merged.

[danharrin has said that my PR would add undesirable complexity and has issues, and suggested us to fix the Repeater hooks](https://github.com/filamentphp/filament/pull/13936#issuecomment-2293090049).

Note: the issue happens not only with Repeaters, but with SpatieMediaLibraryFileUpload as well. It might be happening as well with other components that has **hooks related to database relationships**.

For the SpatieMediaLibraryFileUpload, the issue happens on the [saveRelationshipsUsing hook](https://github.com/filamentphp/filament/blob/8de1a8d0f861d3a824edd0ee89ef455492d18932/packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php#L124) which is called everytime we switch the form active language but it should be called only when user submits the form.

I may look into it further next week.

UPDATE: I'm not finding the time to work on this issue. For now the workaround proposed in this thread is working for me.

**Comment by atmonshi** [comment] 2024-08-16 14:57
thank you @cawecoy for the efforts,
currently I am a bit on a tight schedule with work, so I didn't got a chance to test around.
but I am following the process.

**Comment by atmonshi** [comment] 2024-09-13 15:44
hey everyone
so :)

for now, the changes on #9 will allow us to **store** uploaded files and relations, as long as we **save before** switching the local. (btw there is a shortcut on the forms (ctrl+s))

not prefect, yes. but at least now its usable.

next is working on persist the data when the user switch the local and store the other locals not only the active one.

**Comment by atmonshi** [comment] 2024-09-13 15:47
[tagged](https://github.com/lara-zeus/translatable/releases/tag/v3.3.0)

**Closed as completed** 2024-09-14 10:28 UTC

**Comment by corazzi** [comment] 2025-08-12 22:38
To sort of work around needing to save before switching (I can't trust the user to do this), I've created a custom locale switcher which will save then switch the locale.

In the resource's edit page:

```php
    protected function getHeaderActions(): array
    {
        $switchLocaleActions = array_map(function (string $locale) {
            return Actions\Action::make("switch_locale_{$locale}")
                ->label($locale)
                ->action(function () use ($locale) {
                    $oldLocale = $this->getActiveFormsLocale();

                    /** @var SpatieLaravelTranslatablePlugin $plugin */
                    $plugin = filament('spatie-laravel-translatable');
                    $localeLabel = $plugin->getLocaleLabel($oldLocale) ?? $oldLocale;

                    $this->form->saveRelationships();
                    $this->save(shouldRedirect: false, shouldSendSavedNotification: false);

                    $this->setActiveLocale($locale);

                    Notification::make("saved_{$locale}")
                        ->title(trans('filament-actions::edit.single.notifications.saved.title').' '.$localeLabel)
                        ->success()
                        ->send();
                });
        }, self::$resource::getTranslatableLocales());

        return [
            Actions\ActionGroup::make($switchLocaleActions)
                ->button()
                ->icon('heroicon-o-language')
                ->label('Save and Switch Language'),
        ];
    }
```

It will save and show a notification indicating which language has been saved. This is when switching from English to Japanese, for example:

<img width="972" height="648" alt="Image" src="https://github.com/user-attachments/assets/3c55e6fb-fbaf-4d9d-be0a-c4b867876e6b" />

On the resource's create page, I just don't have the locale switcher, so the user has to create the resource first before they can update the other languages. It's not ideal, but it's at least a bit safer in terms of avoiding data loss.

Hopefully this will help somebody.
